### ISSUE TITLE
How to modify wcb?

### ISSUE THREAD

**Issue by usert5432** [BNLIF/wcp-uboone-bdt#3]
Hello everyone,

I have written [an application](https://github.com/usert5432/wcp-uboone-bdt/tree/eval_dlee_devel) to evaluate the DL EE in the framework of `wcp-uboone-bdt`. I managed to compile it successfully, by adding a new file `find_vlneval.py` to the root of `wcp-uboone-bdt` and modifying `wscript` to load it.

However, it is my understanding that I should move this file (`find_vlneval.py`) to the [waf-tools](https://github.com/BNLIF/waf-tools) repository and rebuild the `wcb` tool. Unfortunately, I cannot figure out how to recompile the `wcb` tool from the `waf-tools` repository.

Could you please help me to figure that out?

**Comment by HaiwangYu** [comment]
Great!

The branch I used to compile this wcb is here:
https://github.com/HaiwangYu/waf-tools/tree/wcp-uboone-bdt
After adding `find_vlneval.py` in `wcb.py`, re-compiling should be straightforward as described in the readme:
`./refresh-wcb -o /path/to/your/wire-cell-toolkit/wcb`

**Comment by brettviren** [comment]
@HaiwangYu's fork of `waf-tools` is from WCT, not WCP.  @usert5432 I didn't realize this when I gave you initial guidance and it means I directed you down slightly the a wrong track (to target WCP's `waf-tools` patterns).  But the two are not hugely different.

Also, it makes sense to me to immediately target a PR against @HaiwangYu fork of `waf-tools` instead of WCT's.  But, let's work toward merging this fork back in to WCT's.

Here are a few items of guidance:

- Cosmetically, please rename `find_vlneval.py` to just `vlneval.py`.  The code itself may be pretty close to what WCT's `waf-tools` expects but some tweaks are likely needed. 

- But, even before that know that WCT's `waf-tools` provides a `generic.py` tool which means you may not even need to provide an explicit "tool" `.py` file.  If the dependency is not "too weird" then it can simply be registered in this list:

  https://github.com/WireCell/waf-tools/blob/master/wcb.py#L12

- We will also need a new "tool" (or perhaps just a line in `wcb.py`) to find tensorflow.

**Comment by usert5432** [comment]
Thank you everyone!
